"""Walk S2 Exponent YT activity SYSTEM-WIDE via market PDA sig history.

This replaces the per-wallet, position-PDA-state-based YT extractor with a
proper event-walker that mirrors how Solstice itself indexes YT activity:

  1. For each tracked S2 market (USX-Jun26, eUSX-Jun26), walk the market PDA's
     full sig history.
  2. For each sig, parse inner-ix Exponent emit_cpi events:
       WrapperBuyYt   → +yt_out_amount  (user actively buys YT)
       WrapperSellYt  → -yt_in_amount   (user actively sells YT)
  3. Attribute each event to the event's `buyer` / `seller` pubkey (the
     authoritative user, not affected by CPI signing or stale on-chain state).
  4. Build per-wallet, per-market cumulative YT balance timeline.
  5. Integrate `yt(t) × mult × dt` over the S2 window.

This naturally excludes LP-residue V1 yt_amount (which is generated by LP
operations, not BuyYt), is robust to CPI-routed deposits, and doesn't depend
on the structurally-stale V1 yt_amount field. Same gold-standard pattern as
HOLD USX/eUSX — but anchored on Exponent's emit_cpi events instead of SPL
Transfer events.
"""
import os, sys, json, time, base64, base58, struct, hashlib
from datetime import datetime, UTC
from collections import defaultdict
from concurrent.futures import ThreadPoolExecutor, as_completed

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from rpc_helper import rpc
from snapshot_ts import last_snapshot_ts
import walker_db

S2_START_TS = 1776038400
S2_END_TS   = 1785024000   # cap if walking beyond now

# Jun26 markets mature at 2026-06-01 12:58:19 UTC (api.exponent.finance maturityDateUnixTs)
MATURITY_TS = 1780318699

EXPONENT_PROG = 'ExponentnaRg3CQbW6dqQNZKXp7gtZ9DGMp1cwC4HAS7'

# Anchor event discriminators = sha256("event:<EventName>")[:8]
_BUY_YT_DISC  = hashlib.sha256(b'event:WrapperBuyYtEvent').digest()[:8]
_SELL_YT_DISC = hashlib.sha256(b'event:WrapperSellYtEvent').digest()[:8]

MARKETS = {
    'USX-Jun26': {
        'market': 'BxbiZpzj32nrVGecFy8VQ1HohaW7ryhas1k9aiETDWdm',
        'mult':   30,
        'quest':  'S2_EXPONENT_YIELD_USX_JUN26',
        'base_usd': 1.0,   # USX = $1
        'yt_mint': 'Au8g11nXqXrUAmL14GM3gQnrnJnr4dcpgc5DNAnu9F9s',
    },
    'eUSX-Jun26': {
        'market': 'rBbzpGk3PTX8mvQg95VWJ24EDgvxyDJYrEo9jtauvjP',
        'mult':   15,
        'quest':  'S2_EXPONENT_YIELD_EUSX_JUN26',
        'base_usd': 1.0319, # eUSX/USD (Solstice eusxPrice & Exponent syExchangeRate, May 2026)
        'yt_mint': 'GEYwnvNzqFXrLnNq4riXbn2ASnwU3cF8RXW6wXKHM4sw',
    },
}


def fetch_all_sigs(addr: str) -> list:
    """Walk full sig history newest→oldest, filtering to pre-snapshot only.

    Sigs newer than last_snapshot_ts() are dropped — their flares aren't
    counted by the integration step, so fetching them burns RPC for nothing.
    Pagination decisions use the UNFILTERED batch (otherwise filtering small
    intraday tails of a batch can falsely terminate the loop).

    CRITICAL: an empty result mid-pagination is NOT a reliable end-of-history
    marker — RPC nodes (especially from CI runners) sometimes return [] under
    load even when more sigs exist. Retry 3× before treating empty as terminal.
    """
    import time as _t
    snap = last_snapshot_ts()
    sigs, before = [], None
    while True:
        b = []
        for attempt in range(4):
            p = [addr, {'limit': 1000}]
            if before: p[1]['before'] = before
            r = rpc('getSignaturesForAddress', p, force_refresh=(attempt > 0))
            b = r.get('result') or []
            if b: break
            _t.sleep(0.5 * (attempt + 1))
        if not b: break  # confirmed end of history (or persistent RPC failure)
        raw_batch_len = len(b)
        last_sig = b[-1]['signature']
        # Filter out sigs newer than the snapshot boundary AFTER deciding pagination.
        b = [s for s in b if (s.get('blockTime') or 0) <= snap]
        sigs.extend(b)
        if raw_batch_len < 1000: break
        before = last_sig
    return sigs


def extract_yt_events_from_tx(tx: dict, market_pk: str) -> list:
    """Return list of (ts, user, delta_yt, base_amount) for BuyYt/SellYt events.

    base_amount is the underlying-asset (USX/eUSX) amount, in token units (not USD).
    Caller converts to USD using the market's base_usd peg. Sign:
      BUY  → user paid base, treat as negative USD-flow (cost paid)
      SELL → user received base, treat as positive USD-flow (cost recovered)

    Event payload layout (post-16-byte prefix):
      WrapperBuyYtEvent:   market(32) | buyer(32)  | yt_out(8) | base_in(8) | ts(8)
      WrapperSellYtEvent:  seller(32) | market(32) | yt_in(8)  | base_out(8)| ts(8)
    """
    meta = tx.get('meta') or {}
    if meta.get('err'): return []
    out = []
    for grp in (meta.get('innerInstructions') or []):
        for ix in (grp.get('instructions') or []):
            if (ix.get('programId') or ix.get('program')) != EXPONENT_PROG: continue
            d_b58 = ix.get('data')
            if not d_b58: continue
            try: data = base58.b58decode(d_b58)
            except Exception:
                try: data = base64.b64decode(d_b58)
                except Exception: continue
            if len(data) < 104: continue
            disc = data[8:16]
            if disc == _BUY_YT_DISC:
                evt_market = base58.b58encode(data[16:48]).decode()
                buyer = base58.b58encode(data[48:80]).decode()
                yt_amount   = struct.unpack('<Q', data[80:88])[0] / 1e6
                base_amount = struct.unpack('<Q', data[88:96])[0] / 1e6
                ts = struct.unpack('<q', data[96:104])[0]
                if evt_market == market_pk and yt_amount > 0:
                    out.append((ts, buyer, +yt_amount, base_amount))
            elif disc == _SELL_YT_DISC:
                seller = base58.b58encode(data[16:48]).decode()
                evt_market = base58.b58encode(data[48:80]).decode()
                yt_amount   = struct.unpack('<Q', data[80:88])[0] / 1e6
                base_amount = struct.unpack('<Q', data[88:96])[0] / 1e6
                ts = struct.unpack('<q', data[96:104])[0]
                if evt_market == market_pk and yt_amount > 0:
                    out.append((ts, seller, -yt_amount, base_amount))
    return out


def main():
    # Anchor flare integration to LAST 00:00 UTC (Solstice's daily snapshot
    # boundary). Running the walker mid-day must NOT integrate intraday flares
    # or our totals diverge from Solstice's published value.
    now_ts = last_snapshot_ts()   # midnight-UTC cutoff (Solstice snapshot cadence)
    end_ts = min(now_ts, S2_END_TS)
    print(f'S2 window: {datetime.fromtimestamp(S2_START_TS, UTC).strftime("%Y-%m-%d")} → '
          f'{datetime.fromtimestamp(end_ts, UTC).strftime("%Y-%m-%d %H:%M UTC")} '
          f'(midnight cutoff, {(end_ts-S2_START_TS)/86400:.1f} days)\n', flush=True)

    all_results = defaultdict(lambda: defaultdict(float))
    all_events_by_wallet = defaultdict(list)   # wallet → list of all-market events for cache

    for mname, cfg in MARKETS.items():
        market_pk = cfg['market']
        mult = cfg['mult']
        print(f'=== {mname} (mult {mult}, market {market_pk[:12]}…) ===', flush=True)

        sigs = fetch_all_sigs(market_pk)
        print(f'  {len(sigs):,} market sigs', flush=True)

        # Fetch all txs in parallel; extract per-wallet event tuples including base.
        events_by_wallet = defaultdict(list)  # wallet -> [(ts, delta_yt, base_amt, sig), ...]
        def fetch(s):
            try:
                tx = rpc('getTransaction', [s['signature'],
                        {'encoding': 'jsonParsed', 'maxSupportedTransactionVersion': 0}]).get('result')
                if not tx: return []
                evs = extract_yt_events_from_tx(tx, market_pk)
                return [(ts, user, delta, base, s['signature']) for ts, user, delta, base in evs]
            except Exception: return []

        n_done = 0
        with ThreadPoolExecutor(max_workers=24) as ex:
            futs = [ex.submit(fetch, s) for s in sigs]
            for fut in as_completed(futs):
                for ts, user, delta, base, sig in fut.result():
                    events_by_wallet[user].append((ts, delta, base, sig))
                n_done += 1
                if n_done % 1000 == 0: print(f'    {n_done}/{len(sigs)}', flush=True)

        n_users = len(events_by_wallet)
        n_events = sum(len(v) for v in events_by_wallet.values())
        print(f'  {n_users} unique users, {n_events} buy/sell events', flush=True)

        # Cost-basis math: how much USD a wallet has effectively invested in YT.
        # Pre-S2 buys time-decay linearly toward $0 at maturity (YT is a decaying
        # claim on remaining yield). So at S2 start, only the residual portion is
        # "still invested." Post-S2 buys count at full USD paid. Sells subtract
        # full USD recovered (1:1, no decay adjustment — they got that real cash).
        BASE_USD = cfg['base_usd']
        def decay_factor(buy_ts: int) -> float:
            if buy_ts >= S2_START_TS: return 1.0
            if MATURITY_TS <= buy_ts: return 0.0
            return max(0.0, (MATURITY_TS - S2_START_TS) / (MATURITY_TS - buy_ts))

        # Integrate flares per wallet + accumulate cost basis
        cost_basis_by_wallet = defaultdict(float)
        for wallet, evs in events_by_wallet.items():
            evs.sort(key=lambda e: e[0])

            # Cost basis: walk events in time order, applying decay only to pre-S2 buys.
            cb = 0.0
            for ts, delta, base, sig in evs:
                usd = base * BASE_USD
                if delta > 0:   # BUY: cost paid (decay-adjusted for pre-S2)
                    cb += usd * decay_factor(ts)
                else:           # SELL: cost recovered (1:1)
                    cb -= usd
            cost_basis_by_wallet[wallet] = max(0.0, cb)

            # Initialize carry-in at S2_START_TS from pre-S2 events
            pre_s2_balance = 0.0
            for ts, delta, base, sig in evs:
                if ts < S2_START_TS:
                    pre_s2_balance = max(0.0, pre_s2_balance + delta)
                else: break
            # Rebuild timeline with carry-in at S2_START
            timeline = [(S2_START_TS, pre_s2_balance)]
            balance = pre_s2_balance
            for ts, delta, base, sig in evs:
                if ts < S2_START_TS: continue
                balance = max(0.0, balance + delta)
                timeline.append((ts, balance))
            # Tail
            timeline.append((end_ts, balance))

            # Integrate yt(t) × mult × dt over [S2_START_TS, end_ts]
            flares = 0.0
            for i in range(len(timeline) - 1):
                t0, bal = timeline[i]
                t1, _ = timeline[i + 1]
                if t1 <= t0 or bal <= 0: continue
                flares += bal * mult * (t1 - t0) / 86400.0

            if flares > 0:
                all_results[wallet][cfg['quest']] = flares
            # Track cost basis per quest (so we can attribute per-market in UI).
            if cost_basis_by_wallet[wallet] > 0:
                all_results[wallet][cfg['quest'] + '__cost_usd'] = cost_basis_by_wallet[wallet]

            # Save ALL events for cache (incl. pre-S2 so chart can show the
            # correct carry-in at S2_START rather than starting from zero).
            for ts, delta, base, sig in evs:
                all_events_by_wallet[wallet].append({
                    'ts': ts, 'sig': sig, 'market': market_pk, 'market_label': mname,
                    'yt_delta': delta, 'base_amount': base, 'usd_value': base * BASE_USD,
                    'ix': 'BuyYt' if delta > 0 else 'SellYt',
                })

        q_total = sum(r.get(cfg['quest'], 0) for r in all_results.values())
        print(f'  total {cfg["quest"]}: {q_total:,.0f} flares', flush=True)
        top = sorted([(w, r.get(cfg['quest'], 0)) for w, r in all_results.items()], key=lambda x: -x[1])[:5]
        print(f'  top 5:')
        for w, f in top:
            if f > 0: print(f'    {w}  {f:,.2f}')
        print(flush=True)

        # Coverage: on-chain YT supply vs sum of wallet-tracked final YT balances.
        try:
            sup_r = rpc('getTokenSupply', [cfg['yt_mint']], timeout=15)
            onchain_yt = float((sup_r.get('result') or {}).get('value', {}).get('uiAmount') or 0)
        except Exception:
            onchain_yt = 0.0
        # Sum each wallet's final YT balance for THIS market only.
        tracked_yt = 0.0
        n_holders = 0
        for w_, evs_ in events_by_wallet.items():  # events_by_wallet is per-market
            bal = sum(d for (_, d, _, _) in evs_)
            if bal > 0:
                tracked_yt += bal
                n_holders += 1
        b_usd = cfg.get('base_usd', 1.0)
        walker_db.write_coverage('walk_s2_yt', cfg['quest'],
                                 pool_tvl_usd=onchain_yt * b_usd,
                                 tracked_tvl_usd=tracked_yt * b_usd,
                                 n_positions=n_holders)

    # Save outputs
    out = {w: dict(pq) for w, pq in all_results.items() if pq}
    out_path = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))),
                            'data', 's2_yt_flares.json')
    with open(out_path, 'w') as f: json.dump(out, f, indent=2)
    print(f'Saved {len(out)} wallets to {out_path}')

    # DB — only real quest rows go into walker_outputs (skip the __cost_usd sidecars).
    WALKER_QUESTS = ['S2_EXPONENT_YIELD_USX_JUN26', 'S2_EXPONENT_YIELD_EUSX_JUN26']
    walker_db.prune('walk_s2_yt')
    rows = []
    for w, pq in out.items():
        for q, v in pq.items():
            if q.endswith('__cost_usd'): continue
            if v > 0: rows.append((w, q, v))
    walker_db.upsert_many('walk_s2_yt', rows)
    walker_db.sync_to_wallet_quests('walk_s2_yt', WALKER_QUESTS)
    print(f'DB: walker_outputs={len(rows)} rows; synced to wallet_quests')

    # quest_cache: write a positions_by_market entry so build_daily_totals.py
    # can reconstruct per-day chart values. Schema matches the old position-
    # state cache shape (positions[].timeline) so no chart rebuild needed.
    # We synthesize a single "virtual position" per market per wallet with
    # the BuyYt/SellYt-derived cumulative balance timeline.
    import db as _db
    _db.init()
    snap_count = 0
    # Group events by wallet+market for cache reconstruction
    per_wallet_per_market = defaultdict(lambda: defaultdict(list))
    for wallet, evs in all_events_by_wallet.items():
        for e in evs:
            per_wallet_per_market[wallet][e['market']].append(e)
    # Plus include wallets that had pre-S2 events leading to a carry-in
    # (already captured above via all_events_by_wallet — pre-S2 events were
    # added only as carry-in computation, not stored. Re-walk to include them.)
    # For now, the in-S2 events plus the carry-in implicit in the timeline are
    # enough for the chart.
    for wallet in set(list(all_results.keys()) + list(per_wallet_per_market.keys())):
        positions_by_market = {}
        cost_basis_by_market = {}   # market_pk → {usd_paid, usd_recovered, usd_basis, n_buys, n_sells}
        for market_pk, cfg in MARKETS.items():
            mp = cfg['market']
            evs = per_wallet_per_market.get(wallet, {}).get(mp, [])
            evs = sorted(evs, key=lambda e: e['ts'])
            if not evs: continue
            # Walk FULL event timeline (pre-S2 + S2) so the chart can clip
            # pre-S2 portion to S2_START_TS and pick up the correct carry-in.
            timeline = []
            balance = 0.0
            for e in evs:
                balance = max(0.0, balance + e['yt_delta'])
                timeline.append([e['ts'], balance])
            # Tail extension to current snapshot time so the chart can
            # integrate from last event to end_ts.
            if timeline and timeline[-1][0] < end_ts:
                timeline.append([end_ts, balance])
            if not timeline: continue

            # Cost basis: group-and-decay model. See [[s2-yt-cost-basis-algorithm]]
            # in memory for full spec.
            #
            # Split S1 events into groups separated by SELL→BUY transitions:
            #   - Group with sells: bundle, decay net cash by LAST sell date
            #   - Group with buys only: each buy decayed by its own date
            # S2 events: face-value (buys add, sells subtract).
            # Final cost_basis = max(0, S1_contribution + S2_contribution).
            # Force 0 if wallet has no current YT AND no S2 YT flares earned —
            # handled downstream in the build step where flare totals exist.
            usd_paid_nominal = 0.0
            usd_recovered_total = 0.0
            n_buys = n_sells = 0
            s1_events, s2_events = [], []
            for e in evs:
                usd = e['usd_value']
                if usd <= 0:
                    print(f'  WARN walk_s2_yt: dropping non-positive usd_value event '
                          f'sig={e.get("sig","?")[:8]} usd={usd}', flush=True)
                    continue
                if e['yt_delta'] > 0:
                    usd_paid_nominal += usd
                    n_buys += 1
                else:
                    usd_recovered_total += usd
                    n_sells += 1
                (s1_events if e['ts'] < S2_START_TS else s2_events).append(e)

            # Build S1 groups demarcated by SELL→BUY transitions.
            groups = []
            current = []
            last_was_sell = False
            for e in s1_events:
                is_buy = e['yt_delta'] > 0
                if is_buy and last_was_sell:
                    groups.append(current); current = []
                current.append(e)
                last_was_sell = (not is_buy)
            if current: groups.append(current)

            s1_contrib = 0.0
            for g in groups:
                has_sell = any(e['yt_delta'] < 0 for e in g)
                if has_sell:
                    buys_sum  = sum(e['usd_value'] for e in g if e['yt_delta'] > 0)
                    sells_sum = sum(e['usd_value'] for e in g if e['yt_delta'] < 0)
                    net = buys_sum - sells_sum
                    last_sell_ts = max(e['ts'] for e in g if e['yt_delta'] < 0)
                    decay = min(1.0, (MATURITY_TS - S2_START_TS) / max(1, (MATURITY_TS - last_sell_ts)))
                    s1_contrib += net * decay
                else:
                    for e in g:
                        decay = min(1.0, (MATURITY_TS - S2_START_TS) / max(1, (MATURITY_TS - e['ts'])))
                        s1_contrib += e['usd_value'] * decay

            s2_contrib = (sum(e['usd_value'] for e in s2_events if e['yt_delta'] > 0)
                        - sum(e['usd_value'] for e in s2_events if e['yt_delta'] < 0))

            cost_basis_by_market[mp] = {
                'usd_basis':     max(0.0, s1_contrib + s2_contrib),
                'usd_paid':      usd_paid_nominal,
                'usd_recovered': usd_recovered_total,
                's1_contribution': s1_contrib,
                's2_contribution': s2_contrib,
                'n_buys':        n_buys,
                'n_sells':       n_sells,
                'n_groups_s1':   len(groups),
            }

            positions_by_market[mp] = [{
                'pubkey': f'{mp[:12]}_yt_synthetic',
                'timeline': timeline,
                'current_yt': balance,
                'method': 'event_walked',
                'is_emitting': balance > 0,
            }]
        if not positions_by_market: continue
        cache_payload = {
            'positions_by_market': positions_by_market,
            'cost_basis_by_market': cost_basis_by_market,
            '_watermark': {'slot': 0, 'ts': now_ts},
            'schema': 'yt_event_walked_v2',
        }
        _db.put_cache(wallet, 'S2_EXPONENT_YT', cache_payload, watermark_ts=now_ts)
        snap_count += 1
    print(f'quest_cache: wrote S2_EXPONENT_YT for {snap_count} wallets')


if __name__ == '__main__':
    main()
