"""Walk S2 Exponent YT activity SYSTEM-WIDE via market PDA sig history.

This replaces the per-wallet, position-PDA-state-based YT extractor with a
proper event-walker that mirrors how Solstice itself indexes YT activity:

  1. For each tracked S2 market (USX-Jun26, eUSX-Jun26), walk the market PDA's
     full sig history.
  2. For each sig, parse inner-ix Exponent emit_cpi events:
       WrapperBuyYt   → +yt_out_amount  (user actively buys YT)
       WrapperSellYt  → -yt_in_amount   (user actively sells YT)
  3. Attribute each event to the event's `buyer` / `seller` pubkey (the
     authoritative user, not affected by CPI signing or stale on-chain state).
  4. Build per-wallet, per-market cumulative YT balance timeline.
  5. Integrate `yt(t) × mult × dt` over the S2 window.

This naturally excludes LP-residue V1 yt_amount (which is generated by LP
operations, not BuyYt), is robust to CPI-routed deposits, and doesn't depend
on the structurally-stale V1 yt_amount field. Same gold-standard pattern as
HOLD USX/eUSX — but anchored on Exponent's emit_cpi events instead of SPL
Transfer events.
"""
import os, sys, json, time, base64, base58, struct, hashlib
from datetime import datetime, UTC
from collections import defaultdict
from concurrent.futures import ThreadPoolExecutor, as_completed

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from rpc_helper import rpc
from snapshot_ts import last_snapshot_ts
import walker_db

S2_START_TS = 1776038400
S2_END_TS   = 1785024000   # cap if walking beyond now

# Maturity timestamps are per-market (V1 Jun01, V2 Sep16). Each MARKETS entry
# carries its own `maturity_ts` and the decay/cost-basis helpers take it
# explicitly. NB: do not reintroduce a module-level MATURITY_TS — V2 markets
# silently broke cost-basis math when they shared the V1 value.
MATURITY_JUN26 = 1780318699   # 2026-06-01 12:58:19 UTC (V1)
MATURITY_SEP26 = 1789552700   # 2026-09-16 09:58:20 UTC (V2)

# Solstice's +50% launch boost on Sep26 markets ran from market launch
# (2026-05-18) until 2026-05-29 00:00 UTC. Pre-cutover accrual uses
# `boost_mult`; post-cutover uses base `mult`. Segments straddling are split.
#
# Multi-wallet verified 2026-06-05 at this exact timestamp:
#   5V9V YT-USX-Sep26  = 11,883,544 (matches Solstice to the cent)
#   6iJD YT-USX-Sep26  = 12,414,940 (matches Solstice to the cent)
#   3KUCs YT-USX-Sep26 =  1,919,390 (matches Solstice to the cent)
# At the original announced 6/02 cutoff all three overshoot by 4-14%.
# See data/user_provided/yt_verification_report.md.
BOOST_END_TS = 1780012800  # 2026-05-29 00:00 UTC

EXPONENT_PROG = 'ExponentnaRg3CQbW6dqQNZKXp7gtZ9DGMp1cwC4HAS7'

# ---- V6 V2-orderbook patch constants ---------------------------------------
EXPONENT_CORE_PROGRAM = 'ExponentnaRg3CQbW6dqQNZKXp7gtZ9DGMp1cwC4HAS7'
ORDERBOOK_PROGRAM     = 'XP1BRLn8eCYSygrd8er5P4GKdzqKbC3DLoSsS5UYVZy'
V2_DEPOSIT_DISC       = bytes.fromhex('180ac9764fb2edf3')
V2_WITHDRAW_DISC      = bytes.fromhex('29fd8b8ea7bb5676')
ANCHOR_WRAP           = bytes.fromhex('e445a52e51cb9a1d')

# ---- V15 XPBook postOffer indexer constants --------------------------------
# Verified empirically via decode of 5V9V postOffer tx 6FoGZHh... (2026-06-02).
# Source: tmp/yt_v2_v15 probe notes. Do NOT change without re-running the
# end-to-end decoder on a known-good tx.
POSTOFFER_EVENT_DISC       = bytes.fromhex('f1535f98c89d90c0')  # 224-byte event under XPBook wrapper
ANCHOR_EVENT_WRAP          = bytes.fromhex('e445a52e51cb9a1d')  # Anchor emit_cpi sentinel
XPBOOK_PROGRAM             = 'XP1BRLn8eCYSygrd8er5P4GKdzqKbC3DLoSsS5UYVZy'
XPBOOK_WRAPPER             = 'XPBookgQTN2p8Yw1C2La35XkPMmZTCEYH77AdReVvK1'
WRAPPER_POSTOFFER_IX_DISC  = bytes.fromhex('1ea5162277d7b03f')  # ix-disc inside wrapper call args
ORDERBOOK_TO_MARKET = {
    'A2yaEiehRCvibSdMWWJtrBdmVCYwGRNSNwg1VwdicthU': '2pZuAPFRJLbT57qJ1ebs8B2ExWwHywyaHUC6Y515BaMm',
    '3oAfRGTEmeDeN8HZYCv2tMeLGMoRpPs4Jyo11wm8JcdV': 'BxbiZpzj32nrVGecFy8VQ1HohaW7ryhas1k9aiETDWdm',
    '3mXbVuMynj21doFXXEauJ2tGDV9kS2Q1SnnQDcgD54Bw': 'EsVGeJ99ADQGwGWLiBEg93xBtmuMjyC4P5zG9bpVMJWf',
}
USX_MINT = '6FrrzDk5mQARGc1TDYoyVnSyRdds1t4PbtohCD6p3tgG'

# Known PDA owners that must never appear as user wallets. Position PDAs owned
# by Exponent program (or orderbook market PDAs themselves) — surfacing them as
# "users" would dump 76K-scale YT onto a single fake wallet.
BLACKLISTED_PDAS = frozenset([
    'A2yaEiehRCvibSdMWWJtrBdmVCYwGRNSNwg1VwdicthU',
    '3mXbVuMynj21doFXXEauJ2tGDV9kS2Q1SnnQDcgD54Bw',
    '3oAfRGTEmeDeN8HZYCv2tMeLGMoRpPs4Jyo11wm8JcdV',
    'BxbiZpzj32nrVGecFy8VQ1HohaW7ryhas1k9aiETDWdm',
    '2pZuAPFRJLbT57qJ1ebs8B2ExWwHywyaHUC6Y515BaMm',
    'EsVGeJ99ADQGwGWLiBEg93xBtmuMjyC4P5zG9bpVMJWf',
    'rBbzpGk3PTX8mvQg95VWJ24EDgvxyDJYrEo9jtauvjP',
])

# market PDA → orderbook PDA. We additionally walk the orderbook PDA's sigs so
# V2 fills (which only touch the orderbook) get picked up.
MARKET_TO_ORDERBOOK_PDA = {
    'BxbiZpzj32nrVGecFy8VQ1HohaW7ryhas1k9aiETDWdm': '3oAfRGTEmeDeN8HZYCv2tMeLGMoRpPs4Jyo11wm8JcdV',
    '2pZuAPFRJLbT57qJ1ebs8B2ExWwHywyaHUC6Y515BaMm': 'A2yaEiehRCvibSdMWWJtrBdmVCYwGRNSNwg1VwdicthU',
    'EsVGeJ99ADQGwGWLiBEg93xBtmuMjyC4P5zG9bpVMJWf': '3mXbVuMynj21doFXXEauJ2tGDV9kS2Q1SnnQDcgD54Bw',
}

# Wrapper market PDA → V2 CORE market PDA. The XPBook-LP-routed mints
# (WrapperProvideLiquidity via the XPBook LP wrapper) bypass the wrapper
# market PDA entirely — they only touch the V2 CORE market. Without walking
# core-market sigs, we miss those mints' depositYtEventV2 events.
# Verified 2026-06-05 from 5V9V's May 30 mint (sig 5WmmQz…) payload[32:64].
MARKET_TO_V2_CORE = {
    '2pZuAPFRJLbT57qJ1ebs8B2ExWwHywyaHUC6Y515BaMm': 'CdUviheAUJaXUryT7JCRDUoNdPXdVvkxNQY1okC6uY8S',
    'EsVGeJ99ADQGwGWLiBEg93xBtmuMjyC4P5zG9bpVMJWf': 'B78XAMSpB5KQqykw9oEec1nFSPeRqYtbTmsxo9EPwAUW',
}

# Resolved owner cache for position PDAs (avoid repeated getAccountInfo calls
# during a single run).
_POSITION_OWNER_CACHE = {}

# Anchor event discriminators = sha256("event:<EventName>")[:8]
# Verified 2026-05-21: V1 and V2 emit identical WrapperBuyYtEvent /
# WrapperSellYtEvent discriminators and 104-byte payload layouts. Same parser
# works for both market versions.
_BUY_YT_DISC  = hashlib.sha256(b'event:WrapperBuyYtEvent').digest()[:8]
_SELL_YT_DISC = hashlib.sha256(b'event:WrapperSellYtEvent').digest()[:8]


def _resolve_position_owner(pda: str):
    """Read the V2 position PDA on-chain and return its owner (bytes 8:40).

    Returns base58 owner pubkey, or None if account missing / can't decode.
    Cached for the duration of the run.
    """
    if pda in _POSITION_OWNER_CACHE:
        return _POSITION_OWNER_CACHE[pda]
    owner = None
    try:
        r = rpc('getAccountInfo', [pda, {'encoding': 'base64'}])
        info = (r or {}).get('result') or {}
        val = info.get('value') or {}
        data = val.get('data')
        if isinstance(data, list) and data and data[0]:
            raw = base64.b64decode(data[0])
            if len(raw) >= 40:
                owner = base58.b58encode(raw[8:40]).decode()
    except Exception:
        owner = None
    _POSITION_OWNER_CACHE[pda] = owner
    return owner


def extract_v2_yt_events_from_tx(tx: dict, market_pk: str) -> list:
    """V2 orderbook-routed YT deposit/withdraw events.

    Walks meta.innerInstructions for emit_cpi-wrapped events:
      - anchor wrap discriminator e445a52e51cb9a1d (8 bytes)
      - then v2 event discriminator (8 bytes): V2_DEPOSIT_DISC or V2_WITHDRAW_DISC
      - payload[64:96]  = position_pda
      - payload[192:200] = amount (u64 LE, YT in 1e6 scaling)
      - payload[200:232] = syExchangeRate (u256 LE = 4× u64 limbs, 1e12 fixed-pt)

    V10: returns base_amount in BASE-ASSET units (NOT pre-multiplied by peg —
    downstream applies cfg['base_usd']). Formula (probe-verified on 5V9V Sep26):
        base_amount = amount_raw * sy_rate / 1e12 / 1e6
    Verified example: amount_raw=76128170724, sy_rate=1e12 → 76128.17 USX.

    Sanity guards (WARN + skip event on violation):
      1. payload size must equal 348 bytes
      2. syExchangeRate must be in [1e11, 1e13]
      3. amount_raw must be < 1e15

    Resolves position PDA → owner via _resolve_position_owner. SKIPs any owner
    in BLACKLISTED_PDAS (PDAs of Exponent / orderbook programs).

    Returns list of (blocktime, owner, signed_base_amount, base_amount).
    """
    meta = tx.get('meta') or {}
    if meta.get('err'): return []
    blocktime = tx.get('blockTime') or 0
    out = []
    for grp in (meta.get('innerInstructions') or []):
        for ix in (grp.get('instructions') or []):
            d_b58 = ix.get('data')
            if not d_b58: continue
            try: data = base58.b58decode(d_b58)
            except Exception:
                try: data = base64.b64decode(d_b58)
                except Exception: continue
            # emit_cpi wrap: first 8 bytes ANCHOR_WRAP, next 8 bytes V2 disc
            if len(data) < 16: continue
            if data[:8] != ANCHOR_WRAP: continue
            disc = data[8:16]
            if disc == V2_DEPOSIT_DISC:
                sign = +1
            elif disc == V2_WITHDRAW_DISC:
                sign = -1
            else:
                continue
            payload = data[16:]
            # Guard 1: payload size must equal 348 bytes (V10 spec).
            if len(payload) != 348:
                print(f'  ⚠️  v2 yt: unexpected payload size {len(payload)} (want 348) — skip event', flush=True)
                continue
            try:
                position_pda = base58.b58encode(payload[64:96]).decode()
                amount_raw = struct.unpack('<Q', payload[192:200])[0]
                limbs = struct.unpack('<4Q', payload[200:232])
                sy_rate = limbs[0] | (limbs[1] << 64) | (limbs[2] << 128) | (limbs[3] << 192)
            except Exception:
                continue
            # Guard 3: amount_raw must be < 1e15.
            if amount_raw >= 10**15:
                print(f'  ⚠️  v2 yt: amount_raw {amount_raw} >= 1e15 — skip event', flush=True)
                continue
            # Guard 2: syExchangeRate must be in [1e11, 1e13].
            if sy_rate < 10**11 or sy_rate > 10**13:
                print(f'  ⚠️  v2 yt: syExchangeRate {sy_rate} outside [1e11, 1e13] — skip event', flush=True)
                continue
            owner = _resolve_position_owner(position_pda)
            if not owner: continue
            if owner in BLACKLISTED_PDAS: continue
            # V18 (2026-06-05): emit yt_amount (not 0) as the delta so the
            # depositYtEventV2 events from mints (Strip+DepositYt) and orderbook
            # fills actually move the user's yield_position balance forward.
            # base_amount stays 0 — true v2 cost basis is injected via the
            # xpbook_offers post-walk fixup (avoids the V16 7× cost over-count).
            yt_amount = amount_raw / 1e6
            base_amount = 0.0
            out.append((blocktime, owner, sign * yt_amount, base_amount))
    return out


def _v2_selftest():
    """Assert known-good position PDA → owner mapping.

    Tested 2026-06-02: position PDA 8zcfwcV1EPGre6VwzJLVjPJSGK9KKbk5oC2PJU7epahY
    owner = 5V9VwuVqXyUeJfa2N7uKxbaV6kX77dJJnowCL6kLojKN.
    """
    expected_owner = '5V9VwuVqXyUeJfa2N7uKxbaV6kX77dJJnowCL6kLojKN'
    pda = '8zcfwcV1EPGre6VwzJLVjPJSGK9KKbk5oC2PJU7epahY'
    actual = _resolve_position_owner(pda)
    assert actual == expected_owner, (
        f'_v2_selftest FAILED: expected {expected_owner}, got {actual}')
    print(f'  _v2_selftest OK: {pda[:12]}… → {expected_owner[:12]}…', flush=True)


def _audit_concentration(market_label: str, events_by_wallet: dict) -> dict:
    """WARN-not-ABORT: if a single wallet's share > 30% AND it's a known PDA,
    log a warning and remove it from the dict. Returns the (possibly filtered)
    events_by_wallet.
    """
    total = 0.0
    per_wallet = {}
    for w, evs in events_by_wallet.items():
        s = sum(d for (_, d, _, _) in evs if d > 0)
        per_wallet[w] = s
        total += max(0.0, s)
    if total <= 0: return events_by_wallet
    filtered = events_by_wallet
    for w, s in per_wallet.items():
        if s <= 0: continue
        share = s / total
        if share > 0.30 and w in BLACKLISTED_PDAS:
            print(f'  ⚠️  concentration audit ({market_label}): {w} = {share*100:.1f}% '
                  f'(blacklisted PDA) — removing from event set', flush=True)
            filtered = {k: v for k, v in filtered.items() if k != w}
    return filtered


def _pre_walk_purge():
    """Remove any previously-persisted walker_events rows whose wallet is a
    known blacklisted PDA. Prior runs (pre-V6) could have stored these.
    """
    try:
        import db as _db_purge
        _db_purge.init()
        c = _db_purge.conn()
        placeholders = ','.join('?' for _ in BLACKLISTED_PDAS)
        params = ['walk_s2_yt', *BLACKLISTED_PDAS]
        cur = c.execute(
            f'DELETE FROM walker_events WHERE walker = ? AND wallet IN ({placeholders})',
            params,
        )
        n = cur.rowcount or 0
        if n > 0:
            print(f'  _pre_walk_purge: removed {n} blacklisted-PDA walker_events rows', flush=True)
    except Exception as e:
        print(f'  ⚠️  _pre_walk_purge failed: {e}', flush=True)


# ============================================================================
# V15 XPBook postOffer indexer
# ----------------------------------------------------------------------------
# Goal: capture USX committed per maker per orderbook so V2 YT cost basis
# (which lives in the orderbook wrapper IX, NOT the position PDA) can be
# attributed to the user who placed the offer.
#
# Architecture mirrors V14 (orderbook PDA sig walk + INSERT OR IGNORE into a
# dedicated table) but with EMPIRICALLY VERIFIED constants:
#   - Event disc f1535f98c89d90c0 (V14 used 198f66ce79aabdf8 → 0 rows)
#   - USX committed comes from the WRAPPER IX call args (26-byte ix data),
#     NOT from the event payload itself
# ============================================================================


def _ensure_xpbook_offers_schema(con):
    """Create xpbook_offers table if missing. Idempotent.

    Schema:
      orderbook   TEXT  -- orderbook PDA (one of ORDERBOOK_TO_MARKET keys)
      sig         TEXT  -- on-chain signature where the postOffer event lived
      blocktime   INT   -- event blockTime
      maker       TEXT  -- pubkey at event payload bytes [16:48]
      usx_committed INT -- u64 from wrapper ix data[9:17] (1e6 units)

    Primary key (orderbook, sig, maker) keeps inserts idempotent across reruns.
    """
    con.execute(
        '''CREATE TABLE IF NOT EXISTS xpbook_offers (
               orderbook     TEXT NOT NULL,
               sig           TEXT NOT NULL,
               blocktime     INTEGER,
               maker         TEXT NOT NULL,
               usx_committed INTEGER NOT NULL DEFAULT 0,
               PRIMARY KEY (orderbook, sig, maker)
           )'''
    )
    con.execute('CREATE INDEX IF NOT EXISTS idx_xpbook_offers_maker '
                'ON xpbook_offers(orderbook, maker)')


def _maker_usx_outflow_raw(tx, maker):
    """Return raw u64 USX outflow (positive = USX paid out) from the maker's
    wallet ATAs in this tx. USX mint hardcoded for USX-on-Solana.
    Used to gate postOffer cost-attribution against cancellation refunds.
    """
    USX_MINT = '6FrrzDk5mQARGc1TDYoyVnSyRdds1t4PbtohCD6p3tgG'
    pre = (tx.get('meta') or {}).get('preTokenBalances') or []
    post = (tx.get('meta') or {}).get('postTokenBalances') or []
    deltas = {}
    for arr, sign in ((pre, -1), (post, +1)):
        for b in arr:
            if b.get('mint') != USX_MINT: continue
            if b.get('owner') != maker: continue
            ai = b.get('accountIndex')
            amt_str = (b.get('uiTokenAmount') or {}).get('amount') or '0'
            try:
                amt = int(amt_str)
            except Exception:
                continue
            deltas[ai] = deltas.get(ai, 0) + sign * amt
    # Sum all NEGATIVE deltas (outflows). Return as raw u64.
    return -sum(d for d in deltas.values() if d < 0)


def _extract_usx_commit_from_wrapper(tx, group_idx, event_ix_idx):
    """Find the wrapper ix in the same inner_ix group that carries the
    postOffer call args. Returns u64 USX amount in 1e6 units, or 0 if not found.

    V18: Multiple wrapper ix discriminators exist (5V9V's tx used
    1ea5162277d7b03f, DDeKrHT's used 5d3db96a227ea83f, others may differ).
    Match STRUCTURALLY instead: ANY 26-byte XPBookgQTN-program ix in the same
    inner group whose first byte is 0x01 and whose u64 at bytes 9-17 is in a
    sane USX range (1e6 .. 1e10 → $1 to $10,000). Pick the first match.
    """
    inner_ixs = (tx.get('meta') or {}).get('innerInstructions') or []
    if group_idx >= len(inner_ixs): return 0
    group = inner_ixs[group_idx]
    for ix in group.get('instructions', []):
        if (ix.get('programId') or ix.get('program')) != XPBOOK_WRAPPER: continue
        d_b58 = ix.get('data')
        if not d_b58: continue
        try:
            data = base58.b58decode(d_b58)
        except Exception:
            try:
                data = base64.b64decode(d_b58)
            except Exception:
                continue
        if len(data) != 26: continue
        if data[0] != 0x01: continue  # wrapper-byte sentinel
        try:
            usx_raw = struct.unpack('<Q', data[9:17])[0]
        except Exception:
            continue
        # Sanity-gate the u64 — must look like a USX amount in 1e6 units.
        if 1_000_000 <= usx_raw <= 10_000_000_000:
            return usx_raw
    return 0


def _index_postoffer_for_orderbook(orderbook_pda, lookback_days=30):
    """Walk orderbook PDA sig history and persist postOffer (maker, usx)
    rows into xpbook_offers.

    Returns the number of rows newly inserted on this call.

    Logic per tx:
      1. For each inner_ix group, iterate its instructions
      2. Find a postOfferEvent: program XPBOOK_WRAPPER, base58 data starting
         with ANCHOR_EVENT_WRAP + POSTOFFER_EVENT_DISC, 224 bytes total
      3. Extract maker pubkey from event payload[16:48]
      4. In the SAME inner_ix group, find the wrapper ix carrying the
         postOffer call args (26-byte data, ix disc = WRAPPER_POSTOFFER_IX_DISC)
      5. INSERT OR IGNORE into xpbook_offers

    lookback_days isn't a hard cutoff — we walk the orderbook's FULL sig
    history (cheap: orderbooks have O(thousands) sigs) and rely on
    INSERT OR IGNORE for idempotence across runs. The kwarg is preserved
    for future use when we wire the freshness watermark.
    """
    import db as _db
    _db.init()
    con = _db.conn()
    _ensure_xpbook_offers_schema(con)

    sigs = fetch_all_sigs(orderbook_pda)
    if not sigs:
        return 0

    rows_inserted = 0

    def _fetch_tx(s):
        for attempt in range(4):
            try:
                r = rpc('getTransaction', [s['signature'],
                        {'encoding': 'jsonParsed', 'maxSupportedTransactionVersion': 0}],
                        force_refresh=(attempt > 0))
                tx = (r or {}).get('result')
                if tx is None: continue
                return tx
            except Exception:
                continue
        return None

    n_scanned = 0
    with ThreadPoolExecutor(max_workers=16) as ex:
        futs = {ex.submit(_fetch_tx, s): s for s in sigs}
        for fut in as_completed(futs):
            sig_str = futs[fut]['signature']
            tx = fut.result()
            n_scanned += 1
            if tx is None: continue
            meta = tx.get('meta') or {}
            if meta.get('err'): continue
            blocktime = tx.get('blockTime') or 0
            inner_ixs = meta.get('innerInstructions') or []
            for grp_idx, grp in enumerate(inner_ixs):
                for ix_idx, ix in enumerate(grp.get('instructions') or []):
                    if (ix.get('programId') or ix.get('program')) != XPBOOK_WRAPPER:
                        continue
                    d_b58 = ix.get('data')
                    if not d_b58: continue
                    try:
                        data = base58.b58decode(d_b58)
                    except Exception:
                        try:
                            data = base64.b64decode(d_b58)
                        except Exception:
                            continue
                    if len(data) != 224: continue
                    if data[0:8] != ANCHOR_EVENT_WRAP: continue
                    if data[8:16] != POSTOFFER_EVENT_DISC: continue
                    # Event payload starts at byte 16; maker at payload[0:32]
                    try:
                        maker = base58.b58encode(data[16:48]).decode()
                    except Exception:
                        continue
                    usx_committed = _extract_usx_commit_from_wrapper(
                        tx, grp_idx, ix_idx)
                    # V18b: gate by ACTUAL maker USX outflow. Cancellations
                    # also emit postOfferEvent + wrapper-ix patterns but the
                    # maker's USX moves IN (refund), not OUT. Only credit cost
                    # when net USX delta on the maker's ATA is negative.
                    if usx_committed > 0:
                        maker_outflow = _maker_usx_outflow_raw(tx, maker)
                        if maker_outflow < usx_committed * 0.5:
                            # No matching debit found — likely a cancel/refund
                            # or a second-emit of the same event. Zero it out.
                            usx_committed = 0
                    try:
                        cur = con.execute(
                            'INSERT OR IGNORE INTO xpbook_offers '
                            '(orderbook, sig, blocktime, maker, usx_committed) '
                            'VALUES (?, ?, ?, ?, ?)',
                            (orderbook_pda, sig_str, blocktime, maker, int(usx_committed)))
                        if cur.rowcount and cur.rowcount > 0:
                            rows_inserted += 1
                    except Exception:
                        continue
    print(f'    indexed {orderbook_pda[:12]}…: scanned {n_scanned:,} txs, '
          f'+{rows_inserted:,} new offer rows', flush=True)
    return rows_inserted


def _lookup_cost_by_owner(orderbook, owner):
    """Best-effort: sum all usx_committed for this maker on this orderbook.

    V15 first cut: lacks fill_amount → uses TOTAL committed as upper bound.
    A future v16 will match by offer_idx once FilledOffersEvent disc is
    pinned. Returns u64 in 1e6 units (callers divide by 1e6 for USD).
    """
    import db as _db
    _db.init()
    con = _db.conn()
    cur = con.execute(
        'SELECT SUM(usx_committed) FROM xpbook_offers '
        'WHERE orderbook = ? AND maker = ?',
        (orderbook, owner))
    row = cur.fetchone()
    if not row or row[0] is None:
        return 0
    return int(row[0])


MARKETS = {
    'USX-Jun26': {
        'market': 'BxbiZpzj32nrVGecFy8VQ1HohaW7ryhas1k9aiETDWdm',
        'mult':   30,
        'quest':  'S2_EXPONENT_YIELD_USX_JUN26',
        'base_usd': 1.0,   # USX = $1
        'yt_mint': 'Au8g11nXqXrUAmL14GM3gQnrnJnr4dcpgc5DNAnu9F9s',
        'maturity_ts': MATURITY_JUN26,
    },
    'eUSX-Jun26': {
        'market': 'rBbzpGk3PTX8mvQg95VWJ24EDgvxyDJYrEo9jtauvjP',
        'mult':   15,
        'quest':  'S2_EXPONENT_YIELD_EUSX_JUN26',
        'base_usd': 1.0319, # eUSX/USD (Solstice eusxPrice & Exponent syExchangeRate, May 2026)
        'yt_mint': 'GEYwnvNzqFXrLnNq4riXbn2ASnwU3cF8RXW6wXKHM4sw',
        'maturity_ts': MATURITY_JUN26,
    },
    'USX-Sep26': {
        # V2 USX-Sep26: market PDA == vault PDA == sig-walk anchor (verified
        # from WrapperBuyYtEvent payload bytes 0-31 in tx 36EkRUH8...).
        'market': '2pZuAPFRJLbT57qJ1ebs8B2ExWwHywyaHUC6Y515BaMm',
        # Time-varying multiplier: Solstice's launch-boost ran from market open
        # (2026-05-18) until 2026-05-29 00:00 UTC. After that, base 30×.
        # Multi-wallet verified — see BOOST_END_TS comment above.
        'mult':       30,
        'boost_mult': 45,
        'boost_end_ts': BOOST_END_TS,
        'quest':  'S2_EXPONENT_YIELD_USX_SEP26',
        'base_usd': 1.0,
        'yt_mint': '6gUU7UXtGgJ3tmeb2gXxQcVeM2L82bg9MzRYxu2YUspu',
        'maturity_ts': MATURITY_SEP26,
        'xpbook_orderbook': 'A2yaEiehRCvibSdMWWJtrBdmVCYwGRNSNwg1VwdicthU',
    },
    'eUSX-Sep26': {
        'market': 'EsVGeJ99ADQGwGWLiBEg93xBtmuMjyC4P5zG9bpVMJWf',
        'mult':       15,
        'boost_mult': 22.5,
        'boost_end_ts': BOOST_END_TS,
        'quest':  'S2_EXPONENT_YIELD_EUSX_SEP26',
        'base_usd': 1.0319,
        'yt_mint': '2wZkuwSiDyHZuuZfS9C9kFkZNsgwHGjKtCxX3B6Ck6EX',
        'maturity_ts': MATURITY_SEP26,
        'xpbook_orderbook': '3mXbVuMynj21doFXXEauJ2tGDV9kS2Q1SnnQDcgD54Bw',
    },
}


def _segment_flares(bal: float, t0: int, t1: int, cfg: dict) -> float:
    """Integrate `bal × mult(t) × dt / 86400` over [t0, t1] for one market cfg.

    Markets with `boost_mult` / `boost_end_ts` keys use the boosted rate up to
    boost_end_ts and base `mult` after. Markets without boost keys behave
    exactly as before (single-rate integration)."""
    if t1 <= t0 or bal <= 0:
        return 0.0
    base_mult = cfg['mult']
    boost_mult = cfg.get('boost_mult')
    boost_end = cfg.get('boost_end_ts')
    peg = cfg.get('base_usd', 1.0)  # eUSX peg (1.0319) or USX (1.0)
    if not boost_mult or not boost_end or t0 >= boost_end:
        return bal * base_mult * peg * (t1 - t0) / 86400.0
    if t1 <= boost_end:
        return bal * boost_mult * peg * (t1 - t0) / 86400.0
    # Straddle: split at boost_end.
    boost_part = bal * boost_mult * peg * (boost_end - t0) / 86400.0
    base_part  = bal * base_mult  * peg * (t1 - boost_end) / 86400.0
    return boost_part + base_part


def _xpbook_yt_escrow_segments(wallet: str, orderbook: str, end_ts: int) -> list:
    """Returns [(ts, cumulative_yt_balance_in_escrow), ...] for this wallet on
    the given XPBook orderbook. Cumulative running sum of signed deltas from
    xpbook_escrow_timeline (asset_kind='YT'). Empty if no events.

    Per Exponent's flares spec, YT escrowed in the orderbook (BuyYt fills
    awaiting claim, SellYt offers awaiting fill/cancel) still earns YT flares.
    """
    if not orderbook: return []
    try:
        import db as _db
        con = _db.conn()
        rows = con.execute(
            "SELECT event_blocktime, delta_raw FROM xpbook_escrow_timeline "
            "WHERE wallet = ? AND asset_kind = 'YT' AND orderbook = ? "
            "AND event_blocktime BETWEEN ? AND ? "
            "ORDER BY event_blocktime, rowid",
            (wallet, orderbook, S2_START_TS, end_ts)).fetchall()
    except Exception:
        return []
    if not rows: return []
    segs = [(S2_START_TS, 0.0)]
    cum = 0.0
    for r in rows:
        cum += r['delta_raw'] / 1e6
        ts = r['event_blocktime']
        if ts == segs[-1][0]:
            segs[-1] = (ts, cum)
        else:
            segs.append((ts, cum))
    return segs


def fetch_all_sigs(addr: str) -> list:
    """Walk full sig history newest→oldest, filtering to pre-snapshot only.

    Sigs newer than last_snapshot_ts() are dropped — their flares aren't
    counted by the integration step, so fetching them burns RPC for nothing.
    Pagination decisions use the UNFILTERED batch (otherwise filtering small
    intraday tails of a batch can falsely terminate the loop).

    CRITICAL: an empty result mid-pagination is NOT a reliable end-of-history
    marker — RPC nodes (especially from CI runners) sometimes return [] under
    load even when more sigs exist. Retry 3× before treating empty as terminal.
    """
    import time as _t
    snap = last_snapshot_ts()
    sigs, before = [], None
    while True:
        b = []
        for attempt in range(4):
            p = [addr, {'limit': 1000}]
            if before: p[1]['before'] = before
            r = rpc('getSignaturesForAddress', p, force_refresh=(attempt > 0))
            b = r.get('result') or []
            if b: break
            _t.sleep(0.5 * (attempt + 1))
        if not b: break  # confirmed end of history (or persistent RPC failure)
        raw_batch_len = len(b)
        last_sig = b[-1]['signature']
        # Filter out sigs newer than the snapshot boundary AFTER deciding pagination.
        b = [s for s in b if (s.get('blockTime') or 0) <= snap]
        sigs.extend(b)
        if raw_batch_len < 1000: break
        before = last_sig
    return sigs


def extract_yt_events_from_tx(tx: dict, market_pk: str) -> list:
    """Return list of (ts, user, delta_yt, base_amount) for BuyYt/SellYt events.

    base_amount is the underlying-asset (USX/eUSX) amount, in token units (not USD).
    Caller converts to USD using the market's base_usd peg. Sign:
      BUY  → user paid base, treat as negative USD-flow (cost paid)
      SELL → user received base, treat as positive USD-flow (cost recovered)

    Event payload layout (post-16-byte prefix):
      WrapperBuyYtEvent:   market(32) | buyer(32)  | yt_out(8) | base_in(8) | ts(8)
      WrapperSellYtEvent:  seller(32) | market(32) | yt_in(8)  | base_out(8)| ts(8)
    """
    meta = tx.get('meta') or {}
    if meta.get('err'): return []
    out = []
    for grp in (meta.get('innerInstructions') or []):
        for ix in (grp.get('instructions') or []):
            if (ix.get('programId') or ix.get('program')) != EXPONENT_PROG: continue
            d_b58 = ix.get('data')
            if not d_b58: continue
            try: data = base58.b58decode(d_b58)
            except Exception:
                try: data = base64.b64decode(d_b58)
                except Exception: continue
            if len(data) < 104: continue
            disc = data[8:16]
            if disc == _BUY_YT_DISC:
                evt_market = base58.b58encode(data[16:48]).decode()
                buyer = base58.b58encode(data[48:80]).decode()
                yt_amount   = struct.unpack('<Q', data[80:88])[0] / 1e6
                base_amount = struct.unpack('<Q', data[88:96])[0] / 1e6
                ts = struct.unpack('<q', data[96:104])[0]
                if evt_market == market_pk and yt_amount > 0:
                    out.append((ts, buyer, +yt_amount, base_amount))
            elif disc == _SELL_YT_DISC:
                seller = base58.b58encode(data[16:48]).decode()
                evt_market = base58.b58encode(data[48:80]).decode()
                yt_amount   = struct.unpack('<Q', data[80:88])[0] / 1e6
                base_amount = struct.unpack('<Q', data[88:96])[0] / 1e6
                ts = struct.unpack('<q', data[96:104])[0]
                if evt_market == market_pk and yt_amount > 0:
                    out.append((ts, seller, -yt_amount, base_amount))
    return out


def main():
    # Anchor flare integration to LAST 00:00 UTC (Solstice's daily snapshot
    # boundary). Running the walker mid-day must NOT integrate intraday flares
    # or our totals diverge from Solstice's published value.
    now_ts = last_snapshot_ts()   # midnight-UTC cutoff (Solstice snapshot cadence)
    end_ts = min(now_ts, S2_END_TS)
    print(f'S2 window: {datetime.fromtimestamp(S2_START_TS, UTC).strftime("%Y-%m-%d")} → '
          f'{datetime.fromtimestamp(end_ts, UTC).strftime("%Y-%m-%d %H:%M UTC")} '
          f'(midnight cutoff, {(end_ts-S2_START_TS)/86400:.1f} days)\n', flush=True)

    # V18 (2026-06-05): V2 orderbook walker. Gated OFF by default — flipping it
    # on caused 23-25% over-credit on USX-Sep26 control wallets that already
    # matched Solstice exactly. Set SOLSTICE_YT_V2_ENABLED=1 to enable.
    v2_enabled = os.environ.get('SOLSTICE_YT_V2_ENABLED') == '1'
    if v2_enabled:
        print('V18 V2-orderbook walker ENABLED', flush=True)
        _v2_selftest()
        _pre_walk_purge()

        # --- V15 XPBook postOffer indexer ------------------------------------
        # Walks each orderbook PDA and persists (maker, usx_committed) rows.
        # Hard-aborts if 0 orderbooks succeed; loud WARN if all succeed but
        # the table stays empty (suggests a disc/decode regression like V14).
        print('V15 XPBook postOffer indexer: starting', flush=True)
        import db as _db_idx
        _db_idx.init()
        _ensure_xpbook_offers_schema(_db_idx.conn())
        orderbooks_succeeded = 0
        total_new_rows = 0
        for ob_pda in ORDERBOOK_TO_MARKET.keys():
            try:
                n_new = _index_postoffer_for_orderbook(ob_pda, lookback_days=30)
                orderbooks_succeeded += 1
                total_new_rows += n_new
            except Exception as e:
                print(f'  ⚠️  V15 index failed for {ob_pda[:12]}…: {e}', flush=True)
        if orderbooks_succeeded == 0:
            raise RuntimeError(
                'V15 XPBook indexer: 0/3 orderbooks succeeded — aborting '
                'rather than running v2 cost-basis lookup against an empty '
                'xpbook_offers table.')
        # Even if no NEW rows this run (could be a re-run), confirm the table
        # actually has data overall. Empty table after a full backfill is the
        # exact V14 failure mode this patch was built to surface.
        try:
            cur = _db_idx.conn().execute('SELECT COUNT(*) FROM xpbook_offers')
            total_rows = cur.fetchone()[0] or 0
        except Exception:
            total_rows = 0
        print(f'V15 indexer summary: {orderbooks_succeeded}/3 orderbooks, '
              f'+{total_new_rows:,} new rows, {total_rows:,} total rows', flush=True)
        if total_rows == 0:
            print('  ⚠️ V15: xpbook_offers is EMPTY after full backfill — '
                  'disc/decode constants may be wrong (V14-style regression)', flush=True)

        # Sanity: 5V9V should have ≥1 indexed offer on USX-Sep26 orderbook.
        con = _db_idx.conn()
        cur = con.execute(
            'SELECT COUNT(*) FROM xpbook_offers WHERE orderbook = ? AND maker = ?',
            ('A2yaEiehRCvibSdMWWJtrBdmVCYwGRNSNwg1VwdicthU',
             '5V9VwuVqXyUeJfa2N7uKxbaV6kX77dJJnowCL6kLojKN'))
        n_5v9v = cur.fetchone()[0]
        print(f'  V15 sanity: 5V9V indexed offer count on USX-Sep26 = {n_5v9v}', flush=True)
        if n_5v9v == 0:
            print('  ⚠️ V15 sanity FAIL: 5V9V has 0 indexed offers — '
                  'disc/decode may still be wrong', flush=True)

    all_results = defaultdict(lambda: defaultdict(float))
    all_events_by_wallet = defaultdict(list)   # wallet → list of all-market events for cache

    for mname, cfg in MARKETS.items():
        market_pk = cfg['market']
        mult = cfg['mult']
        boost_mult = cfg.get('boost_mult')
        mult_tag = f'{boost_mult}× → {mult}×' if boost_mult else f'{mult}×'
        print(f'=== {mname} (mult {mult_tag}, market {market_pk[:12]}…) ===', flush=True)

        sigs = fetch_all_sigs(market_pk)
        print(f'  {len(sigs):,} market sigs', flush=True)

        # V6: union in orderbook PDA sigs (dedupe by signature) so V2 fills
        # that only touch the orderbook are picked up.
        if v2_enabled:
            ob_pda = MARKET_TO_ORDERBOOK_PDA.get(market_pk)
            if ob_pda:
                ob_sigs = fetch_all_sigs(ob_pda)
                seen = {s['signature'] for s in sigs}
                new = [s for s in ob_sigs if s['signature'] not in seen]
                print(f'  {len(ob_sigs):,} orderbook sigs (+{len(new):,} unique)', flush=True)
                sigs = sigs + new

            # V19 (2026-06-05): union in V2 CORE market sigs. XPBook-LP-routed
            # mints (WrapperProvideLiquidity via the XPBook LP wrapper program)
            # bypass the wrapper market PDA and only touch the V2 core. Without
            # this walk we miss those mints' depositYtEventV2 events.
            v2_core = MARKET_TO_V2_CORE.get(market_pk)
            if v2_core:
                core_sigs = fetch_all_sigs(v2_core)
                seen = {s['signature'] for s in sigs}
                new = [s for s in core_sigs if s['signature'] not in seen]
                print(f'  {len(core_sigs):,} v2-core sigs (+{len(new):,} unique)', flush=True)
                sigs = sigs + new

        # Fetch all txs in parallel; extract per-wallet event tuples including base.
        # CRITICAL: silent RPC failures (tx == None or exception) silently dropped
        # entire wallets' BUY events on 2026-05-20, halving USX-Jun26 flares and
        # zeroing eUSX-Jun26. The walker now retries up to 4× with force_refresh
        # on retry attempts, and TRACKS unrecoverable failures so the caller
        # knows the run is incomplete.
        import time as _t
        events_by_wallet = defaultdict(list)  # wallet -> [(ts, delta_yt, base_amt, sig), ...]
        n_failed_fetches = [0]   # mutable counter accessible from threads

        def fetch(s):
            for attempt in range(4):
                try:
                    tx = rpc('getTransaction', [s['signature'],
                            {'encoding': 'jsonParsed', 'maxSupportedTransactionVersion': 0}],
                            force_refresh=(attempt > 0)).get('result')
                    if tx is None:
                        # null result from RPC — retry with force_refresh
                        _t.sleep(0.3 * (attempt + 1))
                        continue
                    evs = extract_yt_events_from_tx(tx, market_pk)
                    merged = [(ts, user, delta, base, s['signature']) for ts, user, delta, base in evs]
                    if v2_enabled:
                        # V2 events return (blocktime, owner, signed_amount, abs_amount).
                        # Use abs_amount as base_amount so existing downstream USD logic still
                        # works (USD = base_amount × base_usd peg).
                        for v_ts, v_owner, v_delta, v_abs in extract_v2_yt_events_from_tx(tx, market_pk):
                            merged.append((v_ts, v_owner, v_delta, v_abs, s['signature']))
                    return merged
                except Exception:
                    _t.sleep(0.3 * (attempt + 1))
                    continue
            # All retries exhausted — count as unrecoverable
            n_failed_fetches[0] += 1
            return []

        n_done = 0
        with ThreadPoolExecutor(max_workers=24) as ex:
            futs = [ex.submit(fetch, s) for s in sigs]
            for fut in as_completed(futs):
                for ts, user, delta, base, sig in fut.result():
                    events_by_wallet[user].append((ts, delta, base, sig))
                n_done += 1
                if n_done % 1000 == 0: print(f'    {n_done}/{len(sigs)}', flush=True)

        n_users = len(events_by_wallet)
        n_events = sum(len(v) for v in events_by_wallet.values())
        print(f'  {n_users} unique users, {n_events} buy/sell events (this run)', flush=True)
        if n_failed_fetches[0] > 0:
            # If we miss > 0.5% of sigs after retries, abort — partial walker
            # output silently corrupts wallet flares (see CWGGhiez-style drops
            # on 2026-05-20 where missing BUY events made balance = 0).
            fail_pct = 100.0 * n_failed_fetches[0] / max(1, len(sigs))
            print(f'  ⚠️  {n_failed_fetches[0]} unrecoverable sig fetches ({fail_pct:.2f}%)', flush=True)
            if fail_pct > 0.5:
                raise RuntimeError(f'walk_s2_yt aborting: {n_failed_fetches[0]} sig fetches '
                                   f'failed after retries ({fail_pct:.2f}% of {len(sigs)} sigs). '
                                   f'Partial data would silently miss BUY events and zero out '
                                   f'wallet flares. Re-run when RPC is healthier.')

        # ============================================================
        # MONOTONIC EVENT STORE — persist every decoded event so a single
        # run's RPC flakes can never overwrite past captures. Cache rebuilds
        # below use the full DB history, not just this run's in-memory state.
        # ============================================================
        import db as _db_es
        _db_es.init()
        events_to_persist = []
        for user, evs in events_by_wallet.items():
            for ts, delta, base, sig in evs:
                events_to_persist.append({
                    'wallet': user, 'market': market_pk, 'sig': sig, 'ts': ts,
                    'kind': 'buy' if delta > 0 else 'sell',
                    'amount_delta': delta, 'base_amount': base,
                })
        n_new = _db_es.put_walker_events('walk_s2_yt', events_to_persist)
        print(f'  walker_events: +{n_new:,} new rows (idempotent), {len(events_to_persist) - n_new:,} already present', flush=True)

        # Replace this run's per-wallet events with the FULL persistent history.
        # Any prior-run event that this run missed (RPC flake) is recovered here.
        full_rows = _db_es.get_walker_events_by_market('walk_s2_yt', market_pk)
        events_by_wallet = defaultdict(list)
        for r in full_rows:
            events_by_wallet[r['wallet']].append((r['ts'], r['amount_delta'], r['base_amount'], r['sig']))
        print(f'  walker_events: {sum(len(v) for v in events_by_wallet.values()):,} total events across '
              f'{len(events_by_wallet):,} wallets (full history)', flush=True)

        # V19: inject XPBook orderbook-derived YT events for Sep26 markets.
        # The market-PDA event walk above only sees WrapperBuyYt/SellYt (AMM activity).
        # XPBook fills + claims fire different events (depositYtV2 + wrapperWithdrawFundsEvent)
        # and are invisible to that walk — so users with orderbook activity (filled BuyYt
        # limit orders, executed SellYt orders) had their YT balance under-counted by
        # ~76K for 5V9V on USX-Sep26. Inject the missing events here:
        #   - BuyYt claim (wrapperWithdrawFundsEvent.amountYtOut > 0) → +YT to maker
        #     timestamped at withdraw blocktime (when YT enters yield_position)
        #   - SellYt fill (xpbook_fills with maker = wallet, side = SellYt) → -YT
        #     timestamped at fill blocktime (when taker takes maker's escrowed YT)
        ob_pk = cfg.get('xpbook_orderbook')
        if ob_pk:
            try:
                con_xb = _db.conn()
                # BuyYt claims: positive YT delta from withdraw events on this orderbook
                for r in con_xb.execute(
                    "SELECT wallet, event_blocktime, -delta_raw amt, event_sig "
                    "FROM xpbook_escrow_timeline "
                    "WHERE orderbook = ? AND asset_kind = 'YT' AND event_kind = 'withdraw' "
                    "AND delta_raw < 0", (ob_pk,)):
                    if r['amt'] > 0:
                        events_by_wallet[r['wallet']].append(
                            (r['event_blocktime'], r['amt'] / 1e6, 0.0, r['event_sig']))
                # SellYt fills: maker loses YT when taker fills their sell offer
                for r in con_xb.execute("""
                    SELECT f.maker, f.fill_blocktime, f.yt_filled_raw amt, f.fill_sig
                    FROM xpbook_fills f
                    JOIN xpbook_offers o ON o.orderbook = f.orderbook
                                       AND o.offer_idx = f.maker_slot
                                       AND o.post_blocktime = (
                                         SELECT MAX(post_blocktime) FROM xpbook_offers
                                         WHERE orderbook = f.orderbook AND offer_idx = f.maker_slot
                                           AND post_blocktime <= f.fill_blocktime)
                    WHERE f.maker IS NOT NULL AND f.orderbook = ? AND o.side = 'SellYt'
                """, (ob_pk,)):
                    if r['amt'] > 0:
                        events_by_wallet[r['maker']].append(
                            (r['fill_blocktime'], -r['amt'] / 1e6, 0.0, r['fill_sig']))
            except Exception as _e:
                print(f'  WARN XPBook YT injection failed for {ob_pk[:14]}..: {_e}', flush=True)

        # V6: concentration audit — drop blacklisted PDAs that own >30% share.
        if v2_enabled:
            events_by_wallet = _audit_concentration(mname, events_by_wallet)

        # ============================================================
        # GLOBAL SUPPLY AUDIT — informational. Compares sum of reconstructed
        # YT (from BuyYt/SellYt events) vs on-chain YT mint supply. A gap
        # is EXPECTED because YT can also be minted by LP operations (not
        # walked by the YT decoder). Track the gap over time so a SUDDEN
        # change suggests walker drift; LP-residue alone is stable.
        # Primary safety is the monotonic walker_events store + per-tx retry.
        # ============================================================
        tracked_yt_sum = 0.0
        for evs in events_by_wallet.values():
            bal = sum(d for (_, d, _, _) in evs)
            if bal > 0: tracked_yt_sum += bal
        try:
            sup_r = rpc('getTokenSupply', [cfg['yt_mint']], timeout=15)
            onchain_yt_supply = float((sup_r.get('result') or {}).get('value', {}).get('uiAmount') or 0)
        except Exception as e:
            onchain_yt_supply = 0.0
            print(f'  ⚠️  getTokenSupply failed ({e}) — skipping supply audit', flush=True)
        if onchain_yt_supply > 0:
            drift_pct = 100.0 * (onchain_yt_supply - tracked_yt_sum) / onchain_yt_supply
            print(f'  supply audit: tracked={tracked_yt_sum:,.2f} vs onchain={onchain_yt_supply:,.2f} '
                  f'(LP-residue {drift_pct:+.2f}% — expected stable)', flush=True)

        # Cost-basis math: how much USD a wallet has effectively invested in YT.
        # Pre-S2 buys time-decay linearly toward $0 at maturity (YT is a decaying
        # claim on remaining yield). So at S2 start, only the residual portion is
        # "still invested." Post-S2 buys count at full USD paid. Sells subtract
        # full USD recovered (1:1, no decay adjustment — they got that real cash).
        BASE_USD = cfg['base_usd']
        MATURITY_TS = cfg['maturity_ts']
        def decay_factor(buy_ts: int) -> float:
            if buy_ts >= S2_START_TS: return 1.0
            if MATURITY_TS <= buy_ts: return 0.0
            return max(0.0, (MATURITY_TS - S2_START_TS) / (MATURITY_TS - buy_ts))

        # Integrate flares per wallet + accumulate cost basis
        cost_basis_by_wallet = defaultdict(float)
        for wallet, evs in events_by_wallet.items():
            evs.sort(key=lambda e: e[0])

            # Cost basis: walk events in time order, applying decay only to pre-S2 buys.
            cb = 0.0
            for ts, delta, base, sig in evs:
                usd = base * BASE_USD
                if delta > 0:   # BUY: cost paid (decay-adjusted for pre-S2)
                    cb += usd * decay_factor(ts)
                else:           # SELL: cost recovered (1:1)
                    cb -= usd
            cost_basis_by_wallet[wallet] = max(0.0, cb)

            # Initialize carry-in at S2_START_TS from pre-S2 events
            pre_s2_balance = 0.0
            for ts, delta, base, sig in evs:
                if ts < S2_START_TS:
                    pre_s2_balance = max(0.0, pre_s2_balance + delta)
                else: break
            # Rebuild timeline with carry-in at S2_START
            timeline = [(S2_START_TS, pre_s2_balance)]
            balance = pre_s2_balance
            for ts, delta, base, sig in evs:
                if ts < S2_START_TS: continue
                balance = max(0.0, balance + delta)
                timeline.append((ts, balance))
            # Tail
            timeline.append((end_ts, balance))

            # Integrate yt(t) × mult × dt over [S2_START_TS, end_ts]
            #   - existing yield_position timeline: linear (current framework behavior)
            #   - XPBook orderbook-escrow timeline: 7-day maturity per S2 docs
            flares = 0.0
            for i in range(len(timeline) - 1):
                t0, bal = timeline[i]
                t1, _ = timeline[i + 1]
                if t1 <= t0 or bal <= 0: continue
                flares += _segment_flares(bal, t0, t1, cfg)

            # XPBook escrow contribution (BuyYt fills awaiting claim + SellYt offers
            # awaiting fill/cancel) — apply 7-day TVL maturity.
            ob = cfg.get('xpbook_orderbook')
            escrow_segs = _xpbook_yt_escrow_segments(wallet, ob, end_ts)
            if escrow_segs:
                # Pre-fetch event_kind per ts so we only anchor run_start on 'post'
                # events (SellYt offer posted). Non-post entries (e.g. taker fills
                # landing YT into escrow) should not reset the 7-day maturity clock.
                event_kinds = {}
                try:
                    import db as _db_kk
                    con_kk = _db_kk.conn()
                    for r in con_kk.execute(
                        "SELECT event_blocktime, event_kind FROM xpbook_escrow_timeline "
                        "WHERE wallet = ? AND asset_kind = 'YT' AND orderbook = ? "
                        "ORDER BY event_blocktime",
                        (wallet, ob)):
                        event_kinds[r['event_blocktime']] = r['event_kind']
                except Exception:
                    event_kinds = {}

                MATURE_SEC = 24 * 3600  # 24h — Solstice's "minimum one day rewarded daily"
                run_start = None
                # Build (t0, bal, t1) segments from escrow timeline
                escrow_segments = []
                for i in range(len(escrow_segs) - 1):
                    ts0, b0 = escrow_segs[i]; ts1, _ = escrow_segs[i+1]
                    if ts1 > end_ts: ts1 = end_ts
                    if ts1 > ts0:
                        escrow_segments.append((ts0, b0, ts1))
                last_ts, last_b = escrow_segs[-1]
                if last_ts < end_ts:
                    escrow_segments.append((last_ts, last_b, end_ts))
                for ts0, bal, ts1 in escrow_segments:
                    if bal > 0:
                        if run_start is None and event_kinds.get(ts0) == 'post':
                            run_start = ts0
                        if run_start is not None:
                            mature_ts = run_start + MATURE_SEC
                            earn_start = max(ts0, mature_ts)
                            if earn_start < ts1:
                                flares += _segment_flares(bal, earn_start, ts1, cfg)
                    else:
                        run_start = None

            if flares > 0:
                all_results[wallet][cfg['quest']] = flares
            # Track cost basis per quest (so we can attribute per-market in UI).
            if cost_basis_by_wallet[wallet] > 0:
                all_results[wallet][cfg['quest'] + '__cost_usd'] = cost_basis_by_wallet[wallet]

            # Save ALL events for cache (incl. pre-S2 so chart can show the
            # correct carry-in at S2_START rather than starting from zero).
            for ts, delta, base, sig in evs:
                all_events_by_wallet[wallet].append({
                    'ts': ts, 'sig': sig, 'market': market_pk, 'market_label': mname,
                    'yt_delta': delta, 'base_amount': base, 'usd_value': base * BASE_USD,
                    'ix': 'BuyYt' if delta > 0 else 'SellYt',
                })

        q_total = sum(r.get(cfg['quest'], 0) for r in all_results.values())
        print(f'  total {cfg["quest"]}: {q_total:,.0f} flares', flush=True)
        top = sorted([(w, r.get(cfg['quest'], 0)) for w, r in all_results.items()], key=lambda x: -x[1])[:5]
        print(f'  top 5:')
        for w, f in top:
            if f > 0: print(f'    {w}  {f:,.2f}')
        print(flush=True)

        # Coverage: on-chain YT supply vs sum of wallet-tracked final YT balances.
        try:
            sup_r = rpc('getTokenSupply', [cfg['yt_mint']], timeout=15)
            onchain_yt = float((sup_r.get('result') or {}).get('value', {}).get('uiAmount') or 0)
        except Exception:
            onchain_yt = 0.0
        # Sum each wallet's final YT balance for THIS market only.
        tracked_yt = 0.0
        n_holders = 0
        for w_, evs_ in events_by_wallet.items():  # events_by_wallet is per-market
            bal = sum(d for (_, d, _, _) in evs_)
            if bal > 0:
                tracked_yt += bal
                n_holders += 1
        b_usd = cfg.get('base_usd', 1.0)
        walker_db.write_coverage('walk_s2_yt', cfg['quest'],
                                 pool_tvl_usd=onchain_yt * b_usd,
                                 tracked_tvl_usd=tracked_yt * b_usd,
                                 n_positions=n_holders)

    # Save outputs
    out = {w: dict(pq) for w, pq in all_results.items() if pq}
    out_path = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))),
                            'data', 's2_yt_flares.json')
    with open(out_path, 'w') as f: json.dump(out, f, indent=2)
    print(f'Saved {len(out)} wallets to {out_path}')

    # DB — only real quest rows go into walker_outputs (skip the __cost_usd sidecars).
    WALKER_QUESTS = ['S2_EXPONENT_YIELD_USX_JUN26', 'S2_EXPONENT_YIELD_EUSX_JUN26',
                     'S2_EXPONENT_YIELD_USX_SEP26', 'S2_EXPONENT_YIELD_EUSX_SEP26']
    walker_db.prune('walk_s2_yt')
    rows = []
    for w, pq in out.items():
        for q, v in pq.items():
            if q.endswith('__cost_usd'): continue
            if v > 0: rows.append((w, q, v))
    walker_db.upsert_many('walk_s2_yt', rows)
    walker_db.sync_to_wallet_quests('walk_s2_yt', WALKER_QUESTS)
    print(f'DB: walker_outputs={len(rows)} rows; synced to wallet_quests')

    # quest_cache: write a positions_by_market entry so build_daily_totals.py
    # can reconstruct per-day chart values. Schema matches the old position-
    # state cache shape (positions[].timeline) so no chart rebuild needed.
    # We synthesize a single "virtual position" per market per wallet with
    # the BuyYt/SellYt-derived cumulative balance timeline.
    import db as _db
    _db.init()
    snap_count = 0
    # Group events by wallet+market for cache reconstruction
    per_wallet_per_market = defaultdict(lambda: defaultdict(list))
    for wallet, evs in all_events_by_wallet.items():
        for e in evs:
            per_wallet_per_market[wallet][e['market']].append(e)
    # Plus include wallets that had pre-S2 events leading to a carry-in
    # (already captured above via all_events_by_wallet — pre-S2 events were
    # added only as carry-in computation, not stored. Re-walk to include them.)
    # For now, the in-S2 events plus the carry-in implicit in the timeline are
    # enough for the chart.
    for wallet in set(list(all_results.keys()) + list(per_wallet_per_market.keys())):
        positions_by_market = {}
        cost_basis_by_market = {}   # market_pk → {usd_paid, usd_recovered, usd_basis, n_buys, n_sells}
        for market_pk, cfg in MARKETS.items():
            mp = cfg['market']
            evs = per_wallet_per_market.get(wallet, {}).get(mp, [])
            evs = sorted(evs, key=lambda e: e['ts'])
            if not evs: continue
            # Walk FULL event timeline (pre-S2 + S2) so the chart can clip
            # pre-S2 portion to S2_START_TS and pick up the correct carry-in.
            timeline = []
            balance = 0.0
            for e in evs:
                balance = max(0.0, balance + e['yt_delta'])
                timeline.append([e['ts'], balance])
            # Tail extension to current snapshot time so the chart can
            # integrate from last event to end_ts.
            if timeline and timeline[-1][0] < end_ts:
                timeline.append([end_ts, balance])
            if not timeline: continue

            # Cost basis: group-and-decay model. See [[s2-yt-cost-basis-algorithm]]
            # in memory for full spec.
            #
            # Split S1 events into groups separated by SELL→BUY transitions:
            #   - Group with sells: bundle, decay net cash by LAST sell date
            #   - Group with buys only: each buy decayed by its own date
            # S2 events: face-value (buys add, sells subtract).
            # Final cost_basis = max(0, S1_contribution + S2_contribution).
            # Force 0 if wallet has no current YT AND no S2 YT flares earned —
            # handled downstream in the build step where flare totals exist.
            usd_paid_nominal = 0.0
            usd_recovered_total = 0.0
            n_buys = n_sells = 0
            s1_events, s2_events = [], []
            for e in evs:
                usd = e['usd_value']
                if usd <= 0:
                    print(f'  WARN walk_s2_yt: dropping non-positive usd_value event '
                          f'sig={e.get("sig","?")[:8]} usd={usd}', flush=True)
                    continue
                if e['yt_delta'] > 0:
                    usd_paid_nominal += usd
                    n_buys += 1
                else:
                    usd_recovered_total += usd
                    n_sells += 1
                (s1_events if e['ts'] < S2_START_TS else s2_events).append(e)

            # Build S1 groups demarcated by SELL→BUY transitions.
            groups = []
            current = []
            last_was_sell = False
            for e in s1_events:
                is_buy = e['yt_delta'] > 0
                if is_buy and last_was_sell:
                    groups.append(current); current = []
                current.append(e)
                last_was_sell = (not is_buy)
            if current: groups.append(current)

            mat_ts = cfg['maturity_ts']
            s1_contrib = 0.0
            for g in groups:
                has_sell = any(e['yt_delta'] < 0 for e in g)
                if has_sell:
                    buys_sum  = sum(e['usd_value'] for e in g if e['yt_delta'] > 0)
                    sells_sum = sum(e['usd_value'] for e in g if e['yt_delta'] < 0)
                    net = buys_sum - sells_sum
                    last_sell_ts = max(e['ts'] for e in g if e['yt_delta'] < 0)
                    decay = min(1.0, (mat_ts - S2_START_TS) / max(1, (mat_ts - last_sell_ts)))
                    s1_contrib += net * decay
                else:
                    for e in g:
                        decay = min(1.0, (mat_ts - S2_START_TS) / max(1, (mat_ts - e['ts'])))
                        s1_contrib += e['usd_value'] * decay

            s2_contrib = (sum(e['usd_value'] for e in s2_events if e['yt_delta'] > 0)
                        - sum(e['usd_value'] for e in s2_events if e['yt_delta'] < 0))

            # V17/V19: inject true v2 cost basis from xpbook_wallet_orderbook_flow
            # (the actual_fill_cost_raw — exact USX consumed by fills, derived from
            # the postOfferEvent.filledOffers.takenAmount events). This replaces the
            # legacy V15 xpbook_offers.usx_committed query (column was renamed in v3
            # of the XPBook transform; the value is the same).
            v2_paid = 0.0
            orderbook_for_market = MARKET_TO_ORDERBOOK_PDA.get(mp)
            if orderbook_for_market:
                try:
                    con = _db.conn()
                    cur = con.execute(
                        "SELECT COALESCE(SUM(actual_fill_cost_raw), 0) "
                        "FROM xpbook_wallet_orderbook_flow "
                        "WHERE orderbook = ? AND wallet = ?",
                        (orderbook_for_market, wallet))
                    row = cur.fetchone()
                    if row and row[0]:
                        v2_paid = row[0] / 1e6   # raw → USX
                except Exception as _e:
                    print(f'  WARN v2 cost lookup failed for {wallet[:10]}/{mp[:10]}: {_e}', flush=True)
                    v2_paid = 0.0

            cost_basis_by_market[mp] = {
                'usd_basis':     max(0.0, s1_contrib + s2_contrib + v2_paid),
                'usd_paid':      usd_paid_nominal + v2_paid,
                'usd_recovered': usd_recovered_total,
                's1_contribution': s1_contrib,
                's2_contribution': s2_contrib,
                'v2_orderbook_contribution': v2_paid,  # V17: separately tracked for audit
                'n_buys':        n_buys,
                'n_sells':       n_sells,
                'n_groups_s1':   len(groups),
            }

            positions_by_market[mp] = [{
                'pubkey': f'{mp[:12]}_yt_synthetic',
                'timeline': timeline,
                'current_yt': balance,
                'method': 'event_walked',
                'is_emitting': balance > 0,
            }]
        if not positions_by_market: continue
        cache_payload = {
            'positions_by_market': positions_by_market,
            'cost_basis_by_market': cost_basis_by_market,
            '_watermark': {'slot': 0, 'ts': now_ts},
            'schema': 'yt_event_walked_v2',
        }
        _db.put_cache(wallet, 'S2_EXPONENT_YT', cache_payload, watermark_ts=now_ts)
        snap_count += 1
    print(f'quest_cache: wrote S2_EXPONENT_YT for {snap_count} wallets')


if __name__ == '__main__':
    main()
