"""Walk S2 Exponent YT activity SYSTEM-WIDE via market PDA sig history.

This replaces the per-wallet, position-PDA-state-based YT extractor with a
proper event-walker that mirrors how Solstice itself indexes YT activity:

  1. For each tracked S2 market (USX-Jun26, eUSX-Jun26), walk the market PDA's
     full sig history.
  2. For each sig, parse inner-ix Exponent emit_cpi events:
       WrapperBuyYt   → +yt_out_amount  (user actively buys YT)
       WrapperSellYt  → -yt_in_amount   (user actively sells YT)
  3. Attribute each event to the event's `buyer` / `seller` pubkey (the
     authoritative user, not affected by CPI signing or stale on-chain state).
  4. Build per-wallet, per-market cumulative YT balance timeline.
  5. Integrate `yt(t) × mult × dt` over the S2 window.

This naturally excludes LP-residue V1 yt_amount (which is generated by LP
operations, not BuyYt), is robust to CPI-routed deposits, and doesn't depend
on the structurally-stale V1 yt_amount field. Same gold-standard pattern as
HOLD USX/eUSX — but anchored on Exponent's emit_cpi events instead of SPL
Transfer events.
"""
import os, sys, json, time, base64, base58, struct, hashlib
from datetime import datetime, UTC
from collections import defaultdict
from concurrent.futures import ThreadPoolExecutor, as_completed

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from rpc_helper import rpc
import walker_db

S2_START_TS = 1776038400
S2_END_TS   = 1785024000   # cap if walking beyond now

EXPONENT_PROG = 'ExponentnaRg3CQbW6dqQNZKXp7gtZ9DGMp1cwC4HAS7'

# Anchor event discriminators = sha256("event:<EventName>")[:8]
_BUY_YT_DISC  = hashlib.sha256(b'event:WrapperBuyYtEvent').digest()[:8]
_SELL_YT_DISC = hashlib.sha256(b'event:WrapperSellYtEvent').digest()[:8]

MARKETS = {
    'USX-Jun26': {
        'market': 'BxbiZpzj32nrVGecFy8VQ1HohaW7ryhas1k9aiETDWdm',
        'mult':   30,
        'quest':  'S2_EXPONENT_YIELD_USX_JUN26',
    },
    'eUSX-Jun26': {
        'market': 'rBbzpGk3PTX8mvQg95VWJ24EDgvxyDJYrEo9jtauvjP',
        'mult':   15,
        'quest':  'S2_EXPONENT_YIELD_EUSX_JUN26',
    },
}


def fetch_all_sigs(addr: str) -> list:
    sigs, before = [], None
    while True:
        p = [addr, {'limit': 1000}]
        if before: p[1]['before'] = before
        r = rpc('getSignaturesForAddress', p)
        b = r.get('result') or []
        if not b: break
        sigs.extend(b)
        if len(b) < 1000: break
        before = b[-1]['signature']
    return sigs


def extract_yt_events_from_tx(tx: dict, market_pk: str) -> list:
    """Return list of (ts, user, delta_yt) for BuyYt/SellYt events on this market.
    Event payload layout (post-16-byte prefix):
      WrapperBuyYtEvent:   market(32) | buyer(32)  | yt_out(8) | base_in(8) | ts(8)
      WrapperSellYtEvent:  seller(32) | market(32) | yt_in(8)  | base_out(8)| ts(8)
    """
    meta = tx.get('meta') or {}
    if meta.get('err'): return []
    out = []
    for grp in (meta.get('innerInstructions') or []):
        for ix in (grp.get('instructions') or []):
            if (ix.get('programId') or ix.get('program')) != EXPONENT_PROG: continue
            d_b58 = ix.get('data')
            if not d_b58: continue
            try: data = base58.b58decode(d_b58)
            except Exception:
                try: data = base64.b64decode(d_b58)
                except Exception: continue
            if len(data) < 104: continue
            disc = data[8:16]
            if disc == _BUY_YT_DISC:
                evt_market = base58.b58encode(data[16:48]).decode()
                buyer = base58.b58encode(data[48:80]).decode()
                yt_amount = struct.unpack('<Q', data[80:88])[0] / 1e6
                ts = struct.unpack('<q', data[96:104])[0]
                if evt_market == market_pk and yt_amount > 0:
                    out.append((ts, buyer, +yt_amount))
            elif disc == _SELL_YT_DISC:
                seller = base58.b58encode(data[16:48]).decode()
                evt_market = base58.b58encode(data[48:80]).decode()
                yt_amount = struct.unpack('<Q', data[80:88])[0] / 1e6
                ts = struct.unpack('<q', data[96:104])[0]
                if evt_market == market_pk and yt_amount > 0:
                    out.append((ts, seller, -yt_amount))
    return out


def main():
    now_ts = int(time.time())
    end_ts = min(now_ts, S2_END_TS)
    print(f'S2 window: {datetime.fromtimestamp(S2_START_TS, UTC).strftime("%Y-%m-%d")} → now ({(end_ts-S2_START_TS)/86400:.1f} days)\n', flush=True)

    all_results = defaultdict(lambda: defaultdict(float))
    all_events_by_wallet = defaultdict(list)   # wallet → list of all-market events for cache

    for mname, cfg in MARKETS.items():
        market_pk = cfg['market']
        mult = cfg['mult']
        print(f'=== {mname} (mult {mult}, market {market_pk[:12]}…) ===', flush=True)

        sigs = fetch_all_sigs(market_pk)
        print(f'  {len(sigs):,} market sigs', flush=True)

        # Fetch all txs in parallel; extract per-wallet (ts, delta) events
        events_by_wallet = defaultdict(list)  # wallet -> [(ts, delta_yt), ...]
        def fetch(s):
            try:
                tx = rpc('getTransaction', [s['signature'],
                        {'encoding': 'jsonParsed', 'maxSupportedTransactionVersion': 0}]).get('result')
                if not tx: return []
                evs = extract_yt_events_from_tx(tx, market_pk)
                # Add signature info for cache
                return [(ts, user, delta, s['signature']) for ts, user, delta in evs]
            except Exception: return []

        n_done = 0
        with ThreadPoolExecutor(max_workers=24) as ex:
            futs = [ex.submit(fetch, s) for s in sigs]
            for fut in as_completed(futs):
                for ts, user, delta, sig in fut.result():
                    events_by_wallet[user].append((ts, delta, sig))
                n_done += 1
                if n_done % 1000 == 0: print(f'    {n_done}/{len(sigs)}', flush=True)

        n_users = len(events_by_wallet)
        n_events = sum(len(v) for v in events_by_wallet.values())
        print(f'  {n_users} unique users, {n_events} buy/sell events', flush=True)

        # Integrate per wallet
        for wallet, evs in events_by_wallet.items():
            evs.sort(key=lambda e: e[0])
            # Build cumulative balance timeline
            balance = 0.0
            timeline = [(S2_START_TS, 0.0)]  # placeholder; we'll set the carry-in
            for ts, delta, sig in evs:
                balance = max(0.0, balance + delta)
                timeline.append((ts, balance))
            # Initialize carry-in at S2_START_TS from pre-S2 events
            pre_s2_balance = 0.0
            for ts, delta, sig in evs:
                if ts < S2_START_TS:
                    pre_s2_balance = max(0.0, pre_s2_balance + delta)
                else: break
            # Rebuild timeline with carry-in at S2_START
            timeline = [(S2_START_TS, pre_s2_balance)]
            balance = pre_s2_balance
            for ts, delta, sig in evs:
                if ts < S2_START_TS: continue
                balance = max(0.0, balance + delta)
                timeline.append((ts, balance))
            # Tail
            timeline.append((end_ts, balance))

            # Integrate yt(t) × mult × dt over [S2_START_TS, end_ts]
            flares = 0.0
            for i in range(len(timeline) - 1):
                t0, bal = timeline[i]
                t1, _ = timeline[i + 1]
                if t1 <= t0 or bal <= 0: continue
                flares += bal * mult * (t1 - t0) / 86400.0

            if flares > 0:
                all_results[wallet][cfg['quest']] = flares

            # Save ALL events for cache (incl. pre-S2 so chart can show the
            # correct carry-in at S2_START rather than starting from zero).
            for ts, delta, sig in evs:
                all_events_by_wallet[wallet].append({
                    'ts': ts, 'sig': sig, 'market': market_pk, 'market_label': mname,
                    'yt_delta': delta, 'ix': 'BuyYt' if delta > 0 else 'SellYt',
                })

        q_total = sum(r.get(cfg['quest'], 0) for r in all_results.values())
        print(f'  total {cfg["quest"]}: {q_total:,.0f} flares', flush=True)
        top = sorted([(w, r.get(cfg['quest'], 0)) for w, r in all_results.items()], key=lambda x: -x[1])[:5]
        print(f'  top 5:')
        for w, f in top:
            if f > 0: print(f'    {w}  {f:,.2f}')
        print(flush=True)

    # Save outputs
    out = {w: dict(pq) for w, pq in all_results.items() if pq}
    out_path = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))),
                            'data', 's2_yt_flares.json')
    with open(out_path, 'w') as f: json.dump(out, f, indent=2)
    print(f'Saved {len(out)} wallets to {out_path}')

    # DB
    WALKER_QUESTS = ['S2_EXPONENT_YIELD_USX_JUN26', 'S2_EXPONENT_YIELD_EUSX_JUN26']
    walker_db.prune('walk_s2_yt')
    rows = []
    for w, pq in out.items():
        for q, v in pq.items():
            if v > 0: rows.append((w, q, v))
    walker_db.upsert_many('walk_s2_yt', rows)
    walker_db.sync_to_wallet_quests('walk_s2_yt', WALKER_QUESTS)
    print(f'DB: walker_outputs={len(rows)} rows; synced to wallet_quests')

    # quest_cache: write a positions_by_market entry so build_daily_totals.py
    # can reconstruct per-day chart values. Schema matches the old position-
    # state cache shape (positions[].timeline) so no chart rebuild needed.
    # We synthesize a single "virtual position" per market per wallet with
    # the BuyYt/SellYt-derived cumulative balance timeline.
    import db as _db
    _db.init()
    snap_count = 0
    # Group events by wallet+market for cache reconstruction
    per_wallet_per_market = defaultdict(lambda: defaultdict(list))
    for wallet, evs in all_events_by_wallet.items():
        for e in evs:
            per_wallet_per_market[wallet][e['market']].append(e)
    # Plus include wallets that had pre-S2 events leading to a carry-in
    # (already captured above via all_events_by_wallet — pre-S2 events were
    # added only as carry-in computation, not stored. Re-walk to include them.)
    # For now, the in-S2 events plus the carry-in implicit in the timeline are
    # enough for the chart.
    for wallet in set(list(all_results.keys()) + list(per_wallet_per_market.keys())):
        positions_by_market = {}
        for market_pk, cfg in MARKETS.items():
            mp = cfg['market']
            evs = per_wallet_per_market.get(wallet, {}).get(mp, [])
            evs = sorted(evs, key=lambda e: e['ts'])
            if not evs: continue
            # Walk FULL event timeline (pre-S2 + S2) so the chart can clip
            # pre-S2 portion to S2_START_TS and pick up the correct carry-in.
            timeline = []
            balance = 0.0
            for e in evs:
                balance = max(0.0, balance + e['yt_delta'])
                timeline.append([e['ts'], balance])
            # Tail extension to current snapshot time so the chart can
            # integrate from last event to end_ts.
            if timeline and timeline[-1][0] < end_ts:
                timeline.append([end_ts, balance])
            if not timeline: continue
            positions_by_market[mp] = [{
                'pubkey': f'{mp[:12]}_yt_synthetic',
                'timeline': timeline,
                'current_yt': balance,
                'method': 'event_walked',
                'is_emitting': balance > 0,
            }]
        if not positions_by_market: continue
        cache_payload = {
            'positions_by_market': positions_by_market,
            '_watermark': {'slot': 0, 'ts': now_ts},
            'schema': 'yt_event_walked_v1',
        }
        _db.put_cache(wallet, 'S2_EXPONENT_YT', cache_payload, watermark_ts=now_ts)
        snap_count += 1
    print(f'quest_cache: wrote S2_EXPONENT_YT for {snap_count} wallets')


if __name__ == '__main__':
    main()
